### PR TITLE
Added option to use absolute filename instead of relative one

### PR DESCRIPTION
**Pull request by kmontag**

### CODE REVIEW

**Comment by igorw** [comment]
Crap, I completely missed this PR! Is it still relevant?

And damn, we really need a test suite.

**Comment by igorw** [comment]
By the way, this option should receive a default value in parseOptions.

**Comment by kmontag** [comment]
My use case was that I wanted to serve from a particular base directory (e.g. %kernel.root_dir%) most of the time, but occasionally needed to serve files from outside that path (e.g. stuff generated and stored in /tmp).  

But I haven't touched the project in awhile, and I'm not sure if this is still relevant, or if it's something you want to support - you can make the call :)

**Comment by igorw** [comment]
Alright, I will close this PR then and keep #8 open. If somebody has a real use case for it and needs the change, I will consider the feature.

Thanks for getting back to me.

**Pull request closed without merging**
